services:
  api:
    container_name: hbt-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto
      - JWT_SECRET=eyJkYXRhYmFzZVVhbt6InBsmith3RncmVzOi8vcG9zdGdy
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: hbt-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
