services:
  api:
    container_name: hbt-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto
      - JWT_SECRET=eyJkYXRhYmFzZVVhbt6InBsmith3RncmVzOi8vcG9zdGdy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INTERNAL_API_KEY=a733017a550d5f7b54b327be8eed
      - TZ=America/Sao_Paulo
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: hbt-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hbt-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
